openapi: 3.0.3
info:
  title: Health Paths
  version: 1.0.0

paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: getHealth
      tags:
        - health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/HealthResponse'
