package: health
generate:
  gin-server: true
  models: true
  embedded-spec: true
output: pkg/api/health/health.gen.go
output-options:
  skip-prune: true
import-mapping:
  ./schemas/HealthResponse.yaml: oapi-codegen-layout/pkg/api/models
