package: products
generate:
  gin-server: true
  models: true
  embedded-spec: true
output: pkg/api/products/products.gen.go
output-options:
  skip-prune: true
import-mapping:
  ./schemas/Product.yaml: oapi-codegen-layout/pkg/api/models
  ./schemas/CreateProductRequest.yaml: oapi-codegen-layout/pkg/api/models
  ./schemas/UpdateProductRequest.yaml: oapi-codegen-layout/pkg/api/models
  ./schemas/Error.yaml: oapi-codegen-layout/pkg/api/models
