package handlers

import (
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	apimodels "oapi-codegen-layout/pkg/api/models"
	"oapi-codegen-layout/pkg/api/health"
)

// HealthHandler implements the health.ServerInterface generated by oapi-codegen
type HealthHandler struct{}

// NewHealthHandler creates a new health handler
func NewHealthHandler() *HealthHandler {
	return &HealthHandler{}
}

// Ensure HealthHandler implements health.ServerInterface
var _ health.ServerInterface = (*HealthHandler)(nil)

// GetHealth implements the health check endpoint
// (GET /health)
func (h *HealthHandler) GetHealth(c *gin.Context) {
	now := time.Now()
	response := apimodels.HealthResponse{
		Status:    "ok",
		Timestamp: now,
	}
	c.JSON(http.StatusOK, response)
}
