openapi: 3.0.3
info:
  title: Example API
  description: Example API using oapi-codegen with Gin
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Development server

paths:
  /health:
    $ref: "./paths/health.yaml"
  /users:
    $ref: "./paths/users.yaml#/~1users"
  /users/{userId}:
    $ref: "./paths/users.yaml#/~1users~1{userId}"
  /products:
    $ref: "./paths/products.yaml#/~1products"
  /products/{productId}:
    $ref: "./paths/products.yaml#/~1products~1{productId}"

components:
  schemas:
    HealthResponse:
      $ref: "./schemas/HealthResponse.yaml"
    User:
      $ref: "./schemas/User.yaml"
    CreateUserRequest:
      $ref: "./schemas/CreateUserRequest.yaml"
    UpdateUserRequest:
      $ref: "./schemas/UpdateUserRequest.yaml"
    Product:
      $ref: "./schemas/Product.yaml"
    CreateProductRequest:
      $ref: "./schemas/CreateProductRequest.yaml"
    UpdateProductRequest:
      $ref: "./schemas/UpdateProductRequest.yaml"
    Error:
      $ref: "./schemas/Error.yaml"
